---
- name: Download Elasticsearch Exporter binary
  get_url:
    url: "{{ elasticsearch_exporter_download_url }}"
    dest: "/tmp/elasticsearch_exporter-{{ elasticsearch_exporter_version }}.linux-amd64.tar.gz"
  when: not ('/tmp/elasticsearch_exporter-' ~ elasticsearch_exporter_version ~ '.linux-amd64.tar.gz' is file)

- name: Extract Elasticsearch Exporter binary
  unarchive:
    src: "/tmp/elasticsearch_exporter-{{ elasticsearch_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes
  when: not ('/tmp/elasticsearch_exporter-' ~ elasticsearch_exporter_version ~ '.linux-amd64/elasticsearch_exporter' is file)

- name: Move Elasticsearch Exporter binary to install dir
  copy:
    src: "/tmp/elasticsearch_exporter-{{ elasticsearch_exporter_version }}.linux-amd64/elasticsearch_exporter"
    dest: "{{ elasticsearch_exporter_install_dir }}/elasticsearch_exporter"
    mode: '0755'
    remote_src: yes
  when: not (elasticsearch_exporter_install_dir ~ '/elasticsearch_exporter' is file)

- name: Create Elasticsearch Exporter service file
  template:
    src: elasticsearch_exporter.service.j2
    dest: /etc/systemd/system/elasticsearch_exporter.service
  when: not ('/etc/systemd/system/elasticsearch_exporter.service' is file)

- name: Start Elasticsearch Exporter service (VM)
  systemd:
    name: elasticsearch_exporter
    state: started
    enabled: yes
